import Link from "next/link";

export const metadata = {
  title: "AI models · Playrift",
  description: "How Playrift uses AI and game data APIs."
};

export default function AiModelsPage() {
  return (
    <div className="min-h-screen bg-surface text-on-surface">
      <header className="border-b border-outline-variant/20 bg-[#161e2f]">
        <div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-6">
          <Link href="/" className="text-lg font-black tracking-tighter text-[#c0c1ff]">
            Playrift
          </Link>
          <Link
            href="/signup"
            className="font-label text-xs font-bold uppercase tracking-widest text-primary hover:underline"
          >
            Get started
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-4xl font-black tracking-tight text-white">AI &amp; data behind Playrift</h1>
        <p className="mt-4 text-on-surface-variant">
          Playrift mixes your Steam library with public game metadata. Only some flows call a large
          language model.
        </p>

        <section className="mt-12 space-y-4 rounded-xl bg-surface-container-low p-6">
          <h2 className="font-label text-sm uppercase tracking-widest text-secondary-fixed-dim">
            Quick Game Pick
          </h2>
          <p className="text-sm leading-relaxed text-on-surface-variant">
            When you describe what you want to play, we send your prompt plus algorithm shortlists to{" "}
            <strong className="text-on-surface">OpenRouter</strong> using the{" "}
            <strong className="text-on-surface">openai/gpt-4o-mini</strong> model. The model must pick from
            curated candidates so suggestions stay grounded in your taste and RAWG data.
          </p>
        </section>

        <section className="mt-8 space-y-4 rounded-xl bg-surface-container-low p-6">
          <h2 className="font-label text-sm uppercase tracking-widest text-secondary-fixed-dim">
            Rift Suggestions &amp; Discovery Radar
          </h2>
          <p className="text-sm leading-relaxed text-on-surface-variant">
            The main recommendation grid is <strong className="text-on-surface">not</strong> generated by
            an LLM. Scores come from your Steam playtime and genre signals matched against the{" "}
            <strong className="text-on-surface">RAWG</strong> catalog (including multi-platform results).
            Search uses RAWG&apos;s API as well.
          </p>
        </section>

        <section className="mt-8 space-y-4 rounded-xl bg-surface-container-low p-6">
          <h2 className="font-label text-sm uppercase tracking-widest text-secondary-fixed-dim">
            Play together &amp; comparisons
          </h2>
          <p className="text-sm leading-relaxed text-on-surface-variant">
            Library overlap and co-op picks use the same Steam + RAWG pipeline—rules and catalog data, not
            chat models.
          </p>
        </section>

        <p className="mt-12 text-sm text-on-surface-variant">
          Models and providers can change as we improve quality and cost; this page reflects the current
          design of the product.
        </p>

        <div className="mt-10 flex flex-wrap gap-4">
          <Link
            href="/dashboard"
            className="rounded-lg bg-primary px-6 py-3 font-label text-xs font-bold uppercase tracking-widest text-on-primary"
          >
            Open dashboard
          </Link>
          <Link
            href="/"
            className="rounded-lg border border-outline-variant/40 px-6 py-3 font-label text-xs font-bold uppercase tracking-widest text-on-surface transition hover:bg-surface-container-high"
          >
            Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
